### PR TITLE
PaymentProvisioning - Add Tooltips and Refactor Labels

### LINKED ISSUE #717: Add `(optional)` to optional field labels in PaymentProvisioning
As part of a larger body of refactor work to the PaymentProvisioning component - we need to help communicate to users which fields are required and which are optional before the user fails a validation check. 

Let's add `(optional)` to the ends of the labels for optional fields.

### LINKED ISSUE #718: Refactor Labels and Help Text on PaymentProvisioning to use consistent language
Currently blocked by #686 - will be clear to proceed soon. 

We have a large batch of feedback and requests to the language used on the PaymentProvisioning component. 

We will be following along with the requests listed in this document (compiled and provided by @Claudia108 💯 ): [PaymentProvisioning component updates - First Phase](https://docs.google.com/document/d/16ES3alWDP7_-RgwATw9GG_3PDDy-f6kc7yfpAf2xGys/edit?usp=sharing)

That document may be restricted - here is the text from the document for quick reference: 

---------------------------------------------------------------------------------------------------------------------

### Step 1: General Info
- Change title to: **“Business Information”**
- **Business Name**
  - Help text: “Enter this exactly as it appears on your tax records (don't use acronyms or abbreviations unless you registered that way)”
- **Doing Business As**
  - Help text: “Enter this exactly as it appears on your tax records (leave blank if you don't have a registered DBA/trade name)”
- **Industry**
  - Help text: “Describe what you sell”
- **Website URL**
  - Help text: “Don't have a live website? You can use your social media business page, app store link, or staging site URL.”
- **Tax ID**
  - Help text: “Employer Identification Numbers (EINs) are nine digits. The federal tax identification number/EIN issued to you by the IRS. It can be found on your tax returns.”
- **Email address**
  - Change to: “Business email address”

### Step 2: Business Legal Address
- Change title to: **“Legal Address of your Business”**
- Help text: “No PO Boxes”

### Step 3: Additional Questions
- Help text for title: “This information helps us understand the business and identify and monitor trends to safeguard you and your customers."
- **What is the business' estimated annual revenue from its primary business activities?** - no changes
- **What is your business' annual credit card & ACH volume anticipated to process?**
- **On average, how long after paying will your customers typically receive their goods or services?** - no changes
- **Does your business offer recurring payments?**
  - Change: Hide the next field, only show it if the answer is “yes”.
- **What percent of revenue is generated from each recurring payment type offered?**
  - Help text: “For example: 50% monthly, 50% annual”
- **Is this business seasonal?**
  - ~Change label to: “Does your business take registrations?”~
  - ~If answer is yes, show new text input field with label:~ 
    - ~**“What is the anticipated amount of customer funds collected between registration open and start of service?”**~
      - Will need backend change
- **Is there anything else you would like us to know about how your customers pay the business?** - no changes

### Step 4: Representative
- Help text for title: “The representative for your business needs to be someone who has significant control over managing your business’s finance. You will have an opportunity to add owners later in the form.”
- **Title**
  - Help text: “Role at your business, e.g. President, CEO, Treasurer”
- **Date of Birth**
  - Help text: “Must be 18 or older”
- **Address**
  - Help text: “​​Enter your address exactly as stated on your driver's license. No PO Boxes”
- **SSN**
  - Help text: “Enter your full Social Security Number. It is required for Federal OFAC check.”

### Step 5: Owners
- Help text: “For partnerships, LLCs or privately held corporations, the business is required to apply with all individuals with 25% or more ownership to the application. For charities and registered non-profits, the business is required to apply with 1 individual with substantial control over the entity; a board member or director.”
- Repeat help text from fields in Representative form in Owners form!

### Step 6: Bank Information
- Help text: “The Direct Deposit Account is the business bank account where your funds will be deposited. The name of this account must match the registered business name exactly. We are not able to accept personal accounts unless your business is a registered sole proprietorship.”
- **Routing Number**
  - Help text: “A valid routing number is nine digits. Please include any leading or trailing zeroes.”
- **Account Number**
  - Help text: “Please copy the account number as shown on your statement/check. Do not include spaces or dashes.”

### Step 7: Documents
- **Upload FYE Balance Sheets**
  - Help text: “Please provide the balance sheet that corresponds to the last day of your business’ last two fiscal years. For example, 12/31/2022 & 12/31/2023 balance sheets.”
- **Upload FYE Profit and Loss Statements**
  - Help text: “Fiscal Year End Profit and Loss statements for your business’ last two fiscal years. For example, FYE 2022 and FYE 2023 profit and loss statements”
- **Upload Bank Statements**
  - Help text: “The most recent 3 months of your business’ bank statements. The statements must match the legal entity registering for this merchant account.”
- **Upload Voided Check**
  - Help text: “Voided check or bank statement where the legal entity and account number are clearly visible. The check must match the legal entity registering for this merchant account.”
- **Upload Government ID**
  - Help text: “The ID must include a personal address.”
- **Upload SS4 / Article of Incorporation** - no change for now. Future: separate, will need backend change
- **Upload any other documents** - no change

### Step 8: Terms and Conditions
- No change

### PR DESCRIPTION
**Pull request by colganmeanor**
### PaymentProvisioning Tooltips, Label refactors

This PR commits the following changes:

- Adds tooltips to several inputs in PaymentProvisioning component. 
- Refactors some labels and section headers in PaymentProvisioning
- Updates spec tests and snapshots

Links
-----

Closes #717 
Closes #718 

Developer considerations
--------------

- On any task
  - [X] Previous unit and e2e tests are passing

Developer QA steps
--------------------

There is potentially a lot to review here - so please check the linked task for a complete list of requested changes.
[Refactor Labels and Help Text on PaymentProvisioning to use consistent language](https://github.com/justifi-tech/web-component-library/issues/718)

- [x] Test suites pass
- [x] Form should function exactly as before
- [x] Please help check for typos and spelling errors in new tooltips and refactored labels
- [x] Reference linked story above to help check for completion of specific refactor requests
- [x] The following fields should now have (optional) appended to their labels: 
  - [x] Step 2 - Address Line 2
  - [x] Step 3 - Is there anything else you would like us to know about how your customers pay the business? / Last input  
  - [x] Step 4 and 5 - Apartment, Suite, etc.

### CODE REVIEW

File: packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/business-owners-form-step-core.tsx [hunk 1]
```diff
@@ -139,8 +139,11 @@ export class BusinessOwnersFormStepCore {
   render() {
     return (
       <div>
-        <legend>Owners</legend>
-        <hr />
+        <div class="d-flex align-items-center gap-2">
+          <legend class="mb-0">Owners</legend>
+          <form-control-tooltip helpText="For partnerships, LLCs or privately held corporations, the business is required to apply with all individuals with 25% or more ownership to the application. For charities and registered non-profits, the business is required to apply with 1 individual with substantial control over the entity; a board member or director." />
```
Comment (TiagoFuelber) [inline packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/business-owners-form-step-core.tsx:144]: I think there's a `;` after entity?

**Review by TiagoFuelber — APPROVED** [review]
Looks good!

File: packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/business-owners-form-step-core.tsx (hunk 1 above)
Comment (colganmeanor) [reply packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/business-owners-form-step-core.tsx]: Good catch! Thanks, I dont think that was correct. So I updated it as follows:
`the business is required to apply with 1 individual with substantial control over the entity, such as a board member or director.`
